spring.application.name=MySpringBoot4Project

server.port=8080

# MariaDB
spring.datasource.url=jdbc:mariadb://172.17.128.1:3306/lab_db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=lab
spring.datasource.password=lab

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Spring Boot Admin Client
spring.boot.admin.client.url=http://localhost:8090
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://127.0.0.1:5500,http://localhost:5500
