
# Application
spring.application.name=MySpringBoot4Project
server.port=8080

# application-secrets.properties(gitignore ??)? ?? ?? ??.
# ?? ??? ? ??? ??? jwt.secret ? ??? ?? ?? ?? ? == ??? ????
spring.profiles.include=secrets





# Spring-Maven/.ENV ? ??? ??????
# ===========
spring.config.import=optional:file:.env[.properties]



# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}





# MariaDB
# ???? localhost. WSL2 ? ?? ???? ??? ?? ???
# application.properties? ??? ?? ????(DB_HOST ?)?
# application-local.properties(gitignore ??)? ??? ?

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lab_db}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME:lab}
spring.datasource.password=${DB_PASSWORD:lab}




# Spring Boot Admin Client
spring.boot.admin.client.url=${SPRING_BOOT_ADMIN_URL:http://localhost:8090}




# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:5500,http://localhost:5500}




# ===========


# JPA / Hibernate	?? ?? = create , ??? = update , flyway ?? ? = validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
# ?? Flyway? ???? ???? ?? ???? ??
# spring.flyway.enabled=false



# REST API ??????? Open Session in View ????
spring.jpa.open-in-view=false


# Actuator ?? ?? ??? 8080/actuator ? ?? ? json ??? ??? ???? ?? ???? ?? ? ??
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# Code Analysis
analysis.language.max-length=50


